# Generated by Django 6.0.5 on 2026-06-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock for products without sizes. When you add sizes below, per-size stock is used instead and this value is ignored.'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. S, M, L, XL.', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('product', 'label')},
            },
        ),
    ]
